---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    hystrix.enabled: "true"
    provider: "fabric8"
    demo.name: "loanbroker"
    project: "${project.artifactId}"
    version: "${project.version}"
    group: "io.fabric8.kubeflix.examples"
  name: "bank1"
spec:
  ports:
  - port: 80
    protocol: "TCP"
    targetPort: 8080
  selector:
    hystrix.enabled: "true"
    provider: "fabric8"
    bank.id: "bank1"
    demo.name: "loanbroker"
    project: "loanbroker-bank"
    group: "io.fabric8.kubeflix.examples"
  type: "LoadBalancer"
