---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  labels:
    hystrix.enabled: "true"
    provider: "fabric8"
    name: "bank"
    project: "${project.artifactId}"
    version: "${project.version}"
    group: "io.fabric8.kubeflix.examples"
  name: "service-bank"
spec:
  replicas: 1
  selector:
      name: "service-bank"
  template:
    metadata:
      labels:
        hystrix.enabled: "true"
        name: "service-bank"
        bank.id: "bank1"
    spec:
      containers:
      - env:
        - name: "CREDIT_BUREAU_URL"
          value: "http://service-credit-bureau.scb-discovery.svc/eval?ssn={ssn}"
        - name: "SPRING_APPLICATION_NAME"
          value: "bank1"
        - name: "BASE_RATE"
          value: "10"
        - name: "BANK_NAME"
          value: "Bank One"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "BANK_NAME"
          value: "Bank One"
        - name: "BASE_RATE"
          value: "18"
        - name: "BANK_NAME"
          value: "Bank One"
        - name: "BASE_RATE"
          value: "18"
        - name: "BANK_NAME"
          value: "Bank One"
        - name: "BASE_RATE"
          value: "18"
        image: "fabric8/service-bank:${project.version}"
        name: "service-bank"
        ports:
        - containerPort: 8080
          name: "http"
        readinessProbe:
          httpGet:
            path: "/health"
            port: 8080
          initialDelaySeconds: 5
      serviceAccountName: "kubeflix"
