---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  labels:
    hystrix.enabled: "true"
    provider: "fabric8"
    demo.name: "loanbroker"
    project: "${project.artifactId}"
    version: "${project.version}"
    group: "io.fabric8.kubeflix.examples"
  name: "bank1"
spec:
  replicas: 1
  selector:
    matchLabels:
      hystrix.enabled: "true"
      provider: "fabric8"
      bank.id: "bank1"
      demo.name: "loanbroker"
      project: "${project.artifactId}"
      group: "io.fabric8.kubeflix.examples"
  template:
    metadata:
      labels:
        hystrix.enabled: "true"
        provider: "fabric8"
        bank.id: "bank1"
        demo.name: "loanbroker"
        project: "${project.artifactId}"
        version: "${project.version}"
        group: "io.fabric8.kubeflix.examples"
    spec:
      containers:
      - env:
        - name: "SPRING_APPLICATION_NAME"
          value: "bank1"
        - name: "BASE_RATE"
          value: "10"
        - name: "BANK_NAME"
          value: "Bank One"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "BANK_NAME"
          value: "Bank One"
        - name: "BASE_RATE"
          value: "18"
        - name: "BANK_NAME"
          value: "Bank One"
        - name: "BASE_RATE"
          value: "18"
        - name: "BANK_NAME"
          value: "Bank One"
        - name: "BASE_RATE"
          value: "18"
        image: "fabric8/loanbroker-bank:${project.version}"
        name: "loanbroker-bank"
        ports:
        - containerPort: 8080
          name: "http"
        readinessProbe:
          httpGet:
            path: "/health"
            port: 8080
          initialDelaySeconds: 5
      serviceAccountName: "fabric8"
