---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    hystrix.enabled: "true"
    provider: "fabric8"
    name: "service-broker"
    project: "${project.artifactId}"
    version: "${project.version}"
    group: "io.fabric8.kubeflix.examples"
  name: "service-broker"
spec:
  ports:
  - port: 80
    protocol: "TCP"
    targetPort: 8080
  selector:
    hystrix.enabled: "true"
    name: "service-broker"
  type: "LoadBalancer"
