---
apiVersion: "v1"
kind: "Deployment"
metadata:
  labels:
    hystrix.enabled: "true"
    provider: "fabric8"
    name: "service-broker"
    project: "${project.artifactId}"
    version: "${project.version}"
    group: "io.fabric8.kubeflix.examples"
  name: "service-broker"
spec:
  replicas: 1
  selector:
    name: "service-broker"
  template:
    metadata:
      labels:
        hystrix.enabled: "true"
        name: "service-broker"
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "fabric8/service-broker:${project.version}"
        name: "service-broker"
        ports:
        - containerPort: 8080
          name: "http"
        readinessProbe:
          httpGet:
            path: "/ready"
            port: 8080
          initialDelaySeconds: 5
      serviceAccountName: "kubeflix"
