---
apiVersion: "v1"
kind: "Deployment"
metadata:
  labels:
    hystrix.enabled: "true"
    name: "service-credit-bureau"
    project: "${project.artifactId}"
    version: "${project.version}"
    group: "io.fabric8.kubeflix.examples"
  name: "service-credit-bureau"
spec:
  replicas: 1
  selector:
<<<<<<< HEAD
    name: "service-credit-bureau"
=======
  	name: "service-credit-bureau"
>>>>>>> efe7f8bf9d2b0bd4f4a8a5b4c31fa1ebf20d1ab2
  template:
    metadata:
      labels:
        name: "service-credit-bureau"
    spec:
      serviceAccountName: "kubeflix"
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          value: "scb-discovery"
        image: "fabric8/service-credit-bureau:${project.version}"
        name: "service-credit-bureau"
        ports:
        - containerPort: 8080
          name: "http"
        readinessProbe:
          httpGet:
            path: "/ready"
            port: 8080
          initialDelaySeconds: 5
      serviceAccountName: "kubeflix"
