---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  labels:
    hystrix.enabled: "true"
    provider: "fabric8"
    demo.name: "loanbroker"
    project: "${project.artifactId}"
    version: "${project.version}"
    group: "io.fabric8.kubeflix.examples"
  name: "loanbroker-credit-bureau"
spec:
  replicas: 1
  selector:
    matchLabels:
      hystrix.enabled: "true"
      provider: "fabric8"
      demo.name: "loanbroker"
      project: "${project.artifactId}"
      version: "${project.version}"
      group: "io.fabric8.kubeflix.examples"
  template:
    metadata:
      labels:
        hystrix.enabled: "true"
        provider: "fabric8"
        demo.name: "loanbroker"
        project: "${project.artifactId}"
        version: "${project.version}"
        group: "io.fabric8.kubeflix.examples"
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "fabric8/loanbroker-credit-bureau:${project.version}"
        name: "loanbroker-credit-bureau"
        ports:
        - containerPort: 8080
          name: "http"
        readinessProbe:
          httpGet:
            path: "/ready"
            port: 8080
          initialDelaySeconds: 5
      serviceAccountName: "fabric8"
